### ISSUE TITLE
Ignoring ignoreIssueTypes

### ISSUE THREAD

**Issue by jonteohr** [muno92/resharper_inspectcode#382]
The action seems to be ignoring some parameters in my configuration.

```yml
  - name: Inspect code
      uses: muno92/resharper_inspectcode@1.6.11
      with:
        solutionPath: ./C2TT.sln
        minimumSeverity: 'warning'
        ignoreIssueType: LocalizableElement, UnknownProperty
```

And it still throws: `Warning: "[UnknownProperty] Property 'MSBuildToolsVersion' is not defined" on D:\a\C2TT\C2TT\C2TT.csproj(3,177)`
