### ISSUE TITLE
Expose extra command line options

### ISSUE THREAD

**Issue by seanm-fathomhq** [muno92/resharper_inspectcode#420]
Would it be possible to expose the `--no-build` and the `--caches-home` options? I am working in a large solution and trying to bring down the run time of the action with caching and it's a bit tricky at the moment because these options aren't exposed.

**Comment by muno92** [comment]
@seanm-fathomhq 

Add `--no-build` option and `--caches-home` option in version 1.9.0.
https://github.com/muno92/resharper_inspectcode/releases/tag/1.9.0

You can use it as follows.

Example)
```yaml
on: push

jobs:
  inspection:
    runs-on: ubuntu-latest
    name: Inspection
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Restore
        run: dotnet restore
      - name: Inspect code
        uses: muno92/resharper_inspectcode@v1
        with:
          solutionPath: ./YourSolution.sln
          noCache: true
          cachesHome: /path/to/caches_home
```
