### ISSUE TITLE
Allow running inspection with different build configuration

### ISSUE THREAD

**Issue by koosvanw** [muno92/resharper_inspectcode#427]
I have a solution which requires to be build with a different build configuration than the default `debug` `x64` configuration. It would be great if there was support to pass the build configuration as parameters to the action, that would enable this action to be used for more diverse projects.

**Comment by muno92** [comment]
@koosvanw 
Hi.

Thank you for creating issue.

You want the `--properties` parameter like following?
https://www.jetbrains.com/help/resharper/InspectCode.html#project-references-possible-problems-and-solutions
`--properties:Platform=x64;Configuration=Debug`

Is my understanding correct?

**Comment by koosvanw** [comment]
HI @muno92,

Thanks for getting back on this!

Yes, if it would be possible to pass in the `Platform` and `Configuration` values as parameters for the GitHub Actions that would be great! I can already pass `NoBuild`, but that is not enough for the analysis to be executed correctly.

**Comment by muno92** [comment]
@koosvanw 
I added `properties` parameter in version 1.10.0.

Could you try it out?

**Comment by koosvanw** [comment]
That's quick!

I've done some testing but I'm running in a couple of issues which I failed to notice before:

* Passing the argument should be `--properties:Platform=...` while now after `properties` a `=` is used. Changing the equals sign to a colon makes the inspection run. Otherwise it fails because it thinks multiple solutions have been passed,
* In my case the `Platform` contains spaces. When I add that, I have to escape it somehow. If I escape with double quotes like `Platform="My Platform"`, the entire `--properties` line is wrapped in double quotes in the command
* Because of the quoting it is not possible to pass in both Platform and Configuration in 1 go. If I run it manually on the commandline I can pass multiple instances of `--properties` but I'm not sure that's a way forward you'd want to take. In my case I could just pass the Platform, that would be enough, since Configuration will for me always be `Debug`.

**Comment by muno92** [comment]
@koosvanw 
Oh, sorry.  
I mistaken and I fixed it.

How about it?

**Comment by koosvanw** [comment]
Quoting is still off. I have the following sample usage:

```yaml
- name: Inspect code
  uses: muno92/resharper_inspectcode@1.10.1
  with:
    solutionPath: mySolution.sln
    solutionWideAnalysis: false
    noBuild: true
    properties: Platform="Platform with spaces"
```

In order to be working, this should be passed in the command as 

`jb inspectcode ... --properties:Platform="Platform with spaces"`

However it results in:

`jb inspectcode ... "--properties:'Platform=Platform with spaces'`

The double quotes are removed from the value, instead wrapping the full argument. The single quote is now being interpreted as part of the `Platform` value, resulting in the error that there is an invalid character in the `Platform` argument.

The quoting of the passed in parameters should be respected, but somehow it gets changed. I don't know why/where that happens.

I've tried working around it using env vars in the GH Action for example, but I can't get that to work.

**Comment by muno92** [comment]
It's caused by actions/toolkit and I'm trying.

Wait a while.

**Comment by muno92** [comment]
@koosvanw 

I fixed code and succeeded to pass double quote with following yaml.
```yaml
properties: 'Platform=\"Any CPU\"'
```

https://github.com/muno92/resharper_inspectcode/actions/runs/6945237569/job/18894129443
```txt
/home/runner/.dotnet/tools/jb inspectcode --output=result.xml --absolute-paths TestSolution/TestSolution.sln --severity=WARNING --build --properties:Platform="Any CPU"
```

But, this job was failed.

Is it works on your environment?

**Comment by koosvanw** [comment]
@muno92 

Thanks for your time on this.

If I use your yaml code I'm getting the following output:

```
jb.exe inspectcode --output=result.xml --absolute-paths "test solution.sln" --no-swea --severity=HINT --no-build "--properties:Platform=\"Any Cpu)\""
```

I notice that you're running the workflow on an Ubuntu runner, while I'm running on a private Windows runner. I suspect that could be where the difference comes from. Unfortunately I can't run the action on an Ubunty/Linux based runner due to prerequisites which are unavailable on Linux.

Would it be possible to get this working on a Windows based environment?

**Comment by muno92** [comment]
@koosvanw 

I debugged on Windows Runner (windows-latest).

And, maybe, you don't need to use double quote because actions/toolkit wrap quote around the arg which contains space.

I run following job and MSBuild recognized platform `Mixed Platforms`.
```yaml
  e2e_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
      - uses: ./
        with:
          solutionPath: TestSolution/TestSolution.sln
          properties: Platform=Mixed Platforms;Configuration=Debug
```

https://github.com/muno92/resharper_inspectcode/actions/runs/6958995989/job/18935239058
> The specified solution configuration "Debug|Mixed Platforms" is invalid.

Could you try this?
