### ISSUE TITLE
Be able to specify dotnet version

### ISSUE THREAD

**Issue by morgan-cromell** [muno92/resharper_inspectcode#439]
I have found no way to specify what dotnet version to use. Even if I run the `setup-dotnet` action using 7.0.x it will run the inspect code with dotnet 8 which fails for us.

**Comment by muno92** [comment]
Exactly.

I will try.

**Comment by muno92** [comment]
@morgan-cromell 
I added `dotnetVersion` option in version 1.11.0.

```yaml
- name: Setup .NET
  id: setup-dotnet
  uses: actions/setup-dotnet@v3
  with:
    dotnet-version: '8.0.x' # [3.1.x, 5.0.x, 6.0.x, 7.0.x, 8.0.x]
- name: Restore
  run: dotnet restore
- name: Inspect code
  uses: muno92/resharper_inspectcode@v1
  with:
    solutionPath: ./YourSolution.sln
    dotnetVersion: ${{ steps.setup-dotnet.outputs.dotnet-version }}
```

https://github.com/muno92/resharper_inspectcode/actions/runs/6989067636/job/19017282212#step:4:19
> JetBrains Inspect Code 2023.2.3
Running on x64 OS in x64 architecture, .NET 8.0.0 under Ubuntu 22.04.3 LTS
Using toolset version 17.0 from /usr/share/dotnet/sdk/7.0.404

Is this OK?
